version: '3.8'

services:
  desafiowarren.api:
    image: ${DOCKER_REGISTRY-}desafiowarrenapi
    container_name: desafiowarren-api
    build:
      context: .
      dockerfile: DesafioWarren.Api/Dockerfile
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    container_name: mysql

  redis:
    image: redis
    container_name: redis

volumes:
  mysqldata:
    external: false