version: '3.8'

services:
  desafiowarren.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_Kestrel__Certificates__Default__Password=desafiowarren
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/desafiowarren.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${USERPROFILE}/.aspnet/https:/https/
  
  mysql:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=DesafioWarren
      - MYSQL_USER=user
      - MYSQL_PASSWORD=V3rYStR0nGP@ssW0rD
      - MYSQL_ROOT_PASSWORD=aDm1nStR0nGP@ssW0rD
    volumes:
        - mysqldata:/var/lib/mysql